---
title: 'Schildkrötenkrebs'
output:
  html_document:
    code_folding: hide
  pdf_document:
    number_sections: yes
  word_document: default
documentclass: scrreprt
classoption:
- parskip
- oneside
header-includes:
- \usepackage[greek, ngerman, main=english]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage[T1]{fontenc}
- \usepackage{lmodern}
- \usepackage[onehalfspacing]{setspace}
- \usepackage[left=2.50cm, right=2.50cm, top=2.50cm, bottom=2.50cm, bindingoffset=10mm,
  includehead, includefoot]{geometry}
- \usepackage[headsepline]{scrlayer-scrpage}
- \usepackage{url}
- \usepackage[backend=biber, style=authoryear, giveninits=true, maxbibnames=99, uniquename=init,
  maxcitenames=2, hyperref=true, date=year]{biblatex}
- \usepackage{xpatch}
- \usepackage{csquotes}
- \usepackage{amsmath}
- \usepackage{listings}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{multirow}
- \usepackage{rotating}
- \usepackage{subfigure}
- \usepackage{graphicx}
- \usepackage{float}
- \usepackage{acronym}
- \usepackage{lipsum}
- \usepackage{scrhack}
- \usepackage{amsmath}
- \emergencystretch=50pt
- \clubpenalty = 10000
- \widowpenalty = 10000
- \displaywidowpenalty = 10000
- \automark[section]{chapter}
- \renewcommand*{\chaptermarkformat}{}
- \renewcommand*{\sectionmarkformat}{}
- \setkomafont{title}{\sffamily}
- \setkomafont{disposition}{\usekomafont{title}}
- \setkomafont{author}{\usekomafont{title}}
- \setkomafont{date}{\usekomafont{title}}
- \setkomafont{caption}{\sffamily\small}
- \setkomafont{captionlabel}{\usekomafont{caption}\bfseries\small}
- \setkomafont{pagehead}{\normalfont\scshape}
csl: bib/molecular-biology-of-the-cell.csl
bibliography:
- bib/packages.bib
- bib/test.bib
---

<!-- Based on Nicolas Peschkes LaTeX Template for MoBis, if you want further information on the packages just check it here: https://gitlab.com/npeschke/LaTeX-Template-IPMB -->

<!-- your title page -->

```{=tex}
\begin{titlepage}
\centering
    {\Large Ruprecht-Karls-Universität Heidelberg\\
        Fakultät für Biowissenschaften\\
        Bachelorstudiengang Molekulare Biotechnologie\\}

    {\vspace{\stretch{2}}}
    {\usekomafont{title}

        {\Huge ksdflsdjf}

        {\Huge sfdsfd}

        {\Huge sfsf}

    }

    \vspace{\stretch{2}}
    {\Large Data Science Project SoSe 2022}

    \vspace{\stretch{2}}

    {\Large
        \begin{tabular}{rl}
            Autoren & Anna Lange, David Matuschek, Jakob Then, Maren Schneider\\
            Geburtsort & Heidelberg\\
            Abgabetermin &20.07.2022\\
        \end{tabular}
    }

    \vspace{\stretch{1}}

\end{titlepage}
```
<!-- add your chapters here -->

\tableofcontents

```{r child = "chapter/abstract.Rmd"}
```

```{r child = "chapter/introduction.Rmd"}
```

```{r child = "chapter/material_and_methods.Rmd"}
```

```{r child = "chapter/results.Rmd"}
```

```{r child = "chapter/discussion.Rmd"}
```

# References

::: {#refs}
:::

```{r child = "chapter/appendix.Rmd"}
```
