# Introduction

# Introduction

2019 starben 230,242 Menschen in Deutschland an Krebs \[Quelle\] \[[Krebsrate und Krebs-Sterberate in Deutschland (krebsinformationsdienst.de)](https://www.krebsinformationsdienst.de/tumorarten/grundlagen/krebsstatistiken.php)\]. Um Tumore zu erkennen und eine besserer Behandlung zu finden, ist die Entwicklung neuer Behandlungsmethoden von hoher Wichtigkeit. Dazu ist es essenziell die mutationstechnischen uRsachen für Krebsentwicklung zu identifizieren. Dafür können transcriptomic profiling methods wie RNA-seq verendet werden.

The provided data in the following analysis originates from a transcriptomic profiling methods like RNA-seq. Transcriptomic profiling sequences all the RNA that has been generated by transcription of the cells DNA. The difference to sequencing of DNA is, that it only sequences those genes, that are going to be expressed in that cell.

#### RNA-seq

RNA-seq is performed by cleaning of RNA, fragmentation, translation of RNA to cDNA, sequencing of cNDA and comparing with the reference genome. The advantage of RNA-seq is that it includes information about gene expression, that is especially important in the analysis of tumors such as epigenetic changes (e.g. epigenetic gene silencing) or fusion proteins.

The results from RNA-seq used for the analysis originate from the cancer genome atlas (TCGA)

## Thyroid carcinoma 

Thyroid carcinoma (THCA) incidence increased dramatically over the past few years (<https://jamanetwork.com/data/journals/intemed/936342/m_ied170005f1.png>) REFERENCE, deswegen schauen wir uns die Gene, die THCA verursachen im unserer Analyse näher an. Allerdings sind nur 1% der deutschen Tumoren THCA.

Thyroid cancers werden in verschiedene Typen aufgeteilt, der häufigste Typ ist papillary thyroid cancer (PTC) with 80% of total Thyroid cancers. The most common mutation in PTC is the V600E-Mutation of the RAF-Kinase, what causes a constant activation and by intracellular signaling it promotes tumor cell growth and thereby growth of the tumor.

Die Aufgabe der Schilddrüse ist es, Hormone zu sythetisieren und somit Köpertemperatur und Metabolismus zu kontrollieren. Thyroxine spielt dabei eine wichtige Rolle im Metabolismus, indem es die metabolic rate stimuliert. [Thyroxine - Higher - Coordination and control - The human endocrine system - Edexcel - GCSE Biology (Single Science) Revision - Edexcel - BBC Bitesize](https://www.bbc.co.uk/bitesize/guides/z3gxb82/revision/3#:~:text=Thyroxine%20is%20produced%20from%20the%20thyroid%20gland%2C%20which,development.%20Its%20levels%20are%20controlled%20by%20negative%20feedback.) xxx. Was auch als eine underactive thyroid (= hypothyroidsm) bezwichnet wird und zu folgen wie Headaches, Nausea, depression führen kann. In der kommenden Analyse wird die Aktivität des thyroxine biosythese pathways in thyroid cancers untersucht. [Thyroxine Deficiency? 17 Signs - ProgressiveHealth.com](https://www.progressivehealth.com/thyroxine-deficiency.htm)
Dadurch dass man weiß dass Thyroxine nicht vorhanden, kann man das ersetzen

the 3 histological types, was bringt uns das, die 3 Typen zu kennen??

2 Subtypen (differentiated (papilarry fulicular thca, weil die wie ursprünglihce thyroid cells ausshen) undifferentited, sehen einfach anders aus als andere thyroid cells, nicht klar abzugrenzen,

das andere bedeuted aus den

neue klassifikationen nur von PTC (BRAF like und RAS like) 80%s

## Hallmarks of cancer

Hallarks: was sind hallmarks? - Hallmarks sind Eigenschaften von TUmoren, die in jedem Tumor nachgewiesen werden können. Dazu gehören unter anderen die folgenden EIgenschaften: Resisting sell death, inducung angiogenesis, enabling replicative immortality, activating invasion and metastasis evading growth surpressors. Diese wurden zuerst von Hanahan und Weinberg 2011 veröffentlicht. Im laufe der Zeit kommen immer mehr hallmakrs dazu/es werden neue entdeckt. \[Quelle\]

Epigeentic profiles = auch epigenetische veränderungen werden in die Expressionsdate mit inebezogen, das wäre sehr sinnvol für die ANalyse, wird hier aber nicht beachetet

Was ist unsere Fragestellung?? und warum ist genau die so interessant?? und wie haben wir das erreicht=

## Computational tools

Um die Aktivität von Pathways zu vergleichen wurde eine

GSE methods um gene zu analysieren die bei RNA- seq analyse´siert wurden (fangen an mit einer ranked gene list =>x single enrichment score für jedes Geneset (2 genesets werden verglichen also zb normales und tumorgewebe)

#### Gene Set Variation Analysis

The Gene Set Variation Analysis (GSVA) is performed with the same intention as the GSEA, with the difference, that there is no reference expression data needed like in the GSEA. Because there was no expression data provided for comparison in the TCGA analysis, GSVA was used. There a various solutions to perform GSVA, one of them is to z-transform the provided expression data of the analysed tissue, so the mean over all patients of each gene is zero and the standard deviation is 1. The distribution of these z-transformed genes is like a t-distribution and can be used to calculate the log2FC and continue like in the GSEA.

#### Gene Set Enrichment Analysis 

To analyse and compare the activity of pathways a Gene Set Enrichment Analysis (GSEA) is performed. Therefore a reference is needed to compare the activity of certain pathways in tumor tissue with the activity in normal tissue.

First, the log2FC is calculated for each gene and ranked in a vector for each patient, beginning with the highest log2FC. This resulted in a MATRIX/DATAFRAME/LIST. A high log2FC implies, that the the gene is higher expressed in tumor tissue than in normal tissue. In the next step the activity of each pathway in each patient is calculated. Therefore the ranked vectors of each patient containing the log2FCs are used. The function checks for each gen if it is included in the analysed pathway or not. If it is included, the log2FC of that gene is added to the cumulative function, if it is not included, the log2FC is subtracted. This results in a cumulative function, that has a peak at a certain place. In this place of the ranked vector is also a gene located, the expression value of that gene is saved as the enrichment score of the analysed pathway and the patient belonging to the used vector.

GSEA was performed with the package xxx.

#### UMAP (**Uniform Manifold Approximation and Projection for Dimension Reduction)**

The UMAP is a method to reduce the dimension of a multidimensional data set. Compared to the PCA, the structure of the data in higher dimensions is maintained. Thereby the UMAP keeps the overall structure of the data set, therefore clusters are easier to identify.

The problem of the UMAP is, that although the overall structure is conserved, the distance between the individual points is not proportional to the real distance in the data set.

kleine KLumpen sind wahrscheinlcich auch im richtigen RAum zusammen

#### PCA (Principle component analysis)

Reduce the dimension of a given data set. The dimensions are summarized in principal components (PCs) which do not correlate. Because the PCs summarize the dimensions, the first PCs explain most of the variance of the data set and thereby can be selected to explain the data. Still, one has to keep in mind, that by reducing the dimensions, not all of the variance is explained and some of the information is lost in the process. The ideal number of PCs can be determined with an elbow-plot. In our analysis we use a PCA as a foundation for the UMAP, because the UMAP can not work with correlated dimensions. Furthermore it is used to detect the most important pathways, which explain most of the first PCs.

In the analysis, a PCA is performed for the pan cancer analysis on the TCGA gene expression data, to find similarities and differences in pathway activity for each tumor type. Furthermore a PCA is performed for the focused analysis of THCA and normal tissue.

### Jaccard index

The Jaccard index is the Intersection, divided by the union of two sets.

### Our Analysis

In the following 2 analyses are performed, a pan cancer analysis and a focused analysis about THCA.

#### Pan Cancer Analysis

For the pan cancer analysis 3 data sets are provided. One containing expression data of 60,000 genes in 10,000 tumor patients, another one with clinical annotations concerning those patients and one with hallmark pathways and their included genes. In the following analysis this data is cleaned by removing NAs, biotype filtering and low-variance filtering. After that a descriptive analysis is performed. Those two steps lead to the actual analysis, a gene set variation analysis to detect significantly altered pathways compared to the other pathways in tumor tissue. In the end a linear regression analysis is performed to predict pathway activity based on other pathways??? xxx Furthermore a neuronal network is built to improve prediction.

#### Focused analysis on THCA patients

Furthermore a analysis of THCA patients is performed. For this analysis a data set containing the gene expression of 60 patients in tumor an normal tissue and their clinical annotations. First the data is cleaned and described like the pan cancer data, to prepare the data for the gene set variation analysis, which is also performed for the THCA data in the bigger pan cancer data set, to confirm results from the smaller data set. In this analysis a linear regression analysis is performed to predict the activity of thyroxine biosynthesis. The results are also improved with a neuronal network.

## Cancer

You can cite one or multiple authors. One author [@kumar_multiple_2017\] and multiple authors \[@kumar_multiple_2017; @zavidij_single-cell_2020]. Write in **bold** or in *italic* or in both ***bolditalic***. You can also write inline code, e.g. `Seurat::RunUMAP`.

## LUAD

Some information @kumar_multiple_2017

## Computational Tools

### Gene Set Variation Analysis

### Gene Set Enrichment Analysis

### UMAP

### PCA

## Our Analysis

### Pan Cancer

### Focused Analysis

### Related Work
